name: Arch Linux Package Build
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: user/repo:latest

    - name: Build Arch Linux package
      uses: docker://archlinux:latest
      with:
        entrypoint: /bin/bash
        args: -c |
          pacman -Syu --noconfirm --needed base-devel git meson vala mangohud fontconfig glib2 gtk4 libadwaita libgee
          git clone https://github.com/radiolamp/mangojuice.git
          cd mangojuice
          git checkout ${{ github.ref }}
          makepkg -si --noconfirm

    - name: Upload package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: mangojuice-pkg
        path: mangojuice/*.pkg.tar.zst