name: Arch Linux Package Build
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Используем актуальную версию checkout

    - name: Set up Arch Linux environment
      uses: archlinux/setup-arch-action@v2  # Используем официальный action для Arch Linux
      with:
        pacman: |
          base-devel
          git
          meson
          vala
          mangohud
          fontconfig
          glib2
          gtk4
          libadwaita
          libgee

    - name: Build Arch Linux package
      run: |
        # Клонируем репозиторий (если нужно)
        git clone https://github.com/radiolamp/mangojuice.git
        cd mangojuice

        # Переключаемся на нужный тег
        git checkout ${{ github.ref }}

        # Собираем пакет
        makepkg -si --noconfirm

    - name: Upload package as artifact
      uses: actions/upload-artifact@v4  # Используем актуальную версию upload-artifact
      with:
        name: mangojuice-pkg
        path: mangojuice/*.pkg.tar.zst
