name: Build Flatpak

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install Docker
        if: ${{ matrix.arch != 'x86_64' }}
        run: |
          dnf -y install docker

      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install Flatpak runtime and SDK
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y flathub org.gnome.Platform//47
          flatpak install --user -y flathub org.gnome.Sdk//47

      - name: Install MangoHud extension
        run: |
          flatpak install --user -y flathub org.freedesktop.Platform.VulkanLayer.MangoHud//24.08

      - name: Build Flatpak
        run: |
          flatpak-builder --user build-dir build-aux/flatpak/io.github.radiolamp.mangojuice.yml --force-clean --arch=${{ matrix.arch }}

      - name: Export Flatpak bundle
        run: |
          flatpak build-export repo build-dir
          flatpak build-bundle repo io.github.radiolamp.mangojuice-${{ matrix.arch }}.flatpak io.github.radiolamp.mangojuice

      - name: Upload Flatpak bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: io.github.radiolamp.mangojuice-${{ matrix.arch }}.flatpak
          path: io.github.radiolamp.mangojuice-${{ matrix.arch }}.flatpak